import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f9fafb',
  },
  scrollContent: {
    flexGrow: 1,
    paddingHorizontal: 24,
    paddingTop: 80,
    paddingBottom: 40,
  },
  header: {
    alignItems: 'center',
    marginBottom: 48,
  },
  title: {
    fontSize: 28,
    fontWeight: '600',
    color: '#6b7280',
    textAlign: 'center',
    marginBottom: 32,
    letterSpacing: -0.5,
  },
  logoContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 32,
  },
  // OAuth Logo Container for PNG Images
  oauthLogoContainer: {
    width: 20,
    height: 20,
    marginRight: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  logoCircle: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#000',
    marginRight: 12,
  },
  logoText: {
    fontSize: 32,
    fontWeight: 'bold',
    color: '#000',
    letterSpacing: -1,
  },
  subtitle: {
    fontSize: 16,
    color: '#6b7280',
    textAlign: 'center',
    fontWeight: '400',
  },
  loginCard: {
    backgroundColor: '#fff',
    borderRadius: 20,
    marginHorizontal: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
    overflow: 'hidden',
  },
  primaryActions: {
    padding: 0,
  },
  primaryButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 20,
    paddingHorizontal: 24,
    borderBottomWidth: 1,
    borderBottomColor: '#f3f4f6',
    backgroundColor: '#fff',
  },
  emailButton: {
    backgroundColor: '#fff',
  },
  passkeyButton: {
    backgroundColor: '#fff',
    borderBottomWidth: 0,
  },
  primaryButtonIcon: {
    fontSize: 20,
    marginRight: 16,
  },
  primaryButtonText: {
    fontSize: 16,
    fontWeight: '500',
    color: '#111827',
    flex: 1,
  },
  buttonContent: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  buttonArrow: {
    fontSize: 18,
    color: '#9ca3af',
  },
  // Email Icon Styles
  emailIcon: {
    width: 20,
    height: 20,
    marginRight: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  emailEnvelope: {
    width: 18,
    height: 14,
    borderWidth: 1.5,
    borderColor: '#6b7280',
    borderRadius: 4,
    backgroundColor: 'transparent',
    position: 'relative',
    alignItems: 'center',
    justifyContent: 'center',
  },
  emailFlap: {
    position: 'absolute',
    top: 2,
    width: 0,
    height: 0,
    borderLeftWidth: 6,
    borderRightWidth: 6,
    borderTopWidth: 4,
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    borderTopColor: '#6b7280',
  },
  // Phone Icon Styles
  phoneIcon: {
    width: 20,
    height: 20,
    marginRight: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  phoneBody: {
    width: 12,
    height: 18,
    borderWidth: 1.5,
    borderColor: '#6b7280',
    borderRadius: 3,
    backgroundColor: 'transparent',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 2,
  },
  phoneScreen: {
    width: 7,
    height: 10,
    backgroundColor: '#f3f4f6',
    borderRadius: 1,
  },
  phoneHomeButton: {
    width: 3,
    height: 3,
    borderRadius: 1.5,
    borderWidth: 1,
    borderColor: '#6b7280',
    backgroundColor: 'transparent',
  },
  divider: {
    paddingVertical: 24,
    paddingHorizontal: 24,
    backgroundColor: '#f9fafb',
  },
  dividerText: {
    fontSize: 14,
    color: '#6b7280',
    fontWeight: '500',
    textAlign: 'center',
  },
  oauthContainer: {
    backgroundColor: '#fff',
  },
  oauthButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 20,
    paddingHorizontal: 24,
    borderBottomWidth: 1,
    borderBottomColor: '#f3f4f6',
    backgroundColor: '#fff',
  },
  oauthButtonLast: {
    borderBottomWidth: 0,
  },
  oauthContent: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  oauthIcon: {
    fontSize: 20,
    marginRight: 16,
  },
  oauthText: {
    fontSize: 16,
    fontWeight: '500',
    color: '#111827',
    flex: 1,
  },
  recentBadge: {
    backgroundColor: '#f3f4f6',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 4,
    marginRight: 8,
  },
  recentText: {
    fontSize: 12,
    color: '#6b7280',
    fontWeight: '500',
  },
  errorContainer: {
    backgroundColor: '#fef2f2',
    borderRadius: 12,
    padding: 20,
    margin: 24,
    borderLeftWidth: 4,
    borderLeftColor: '#ef4444',
  },
  errorIcon: {
    fontSize: 20,
    marginRight: 12,
  },
  errorText: {
    flex: 1,
    fontSize: 14,
    color: '#dc2626',
    fontWeight: '500',
  },
  configSection: {
    backgroundColor: '#fff',
    borderRadius: 20,
    marginHorizontal: 4,
    marginTop: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  configToggle: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 20,
    paddingHorizontal: 24,
    borderBottomWidth: 1,
    borderBottomColor: '#f3f4f6',
  },
  configToggleText: {
    fontSize: 16,
    fontWeight: '500',
    color: '#111827',
  },
  configToggleIcon: {
    fontSize: 16,
    color: '#6b7280',
  },
  configDetails: {
    padding: 24,
    paddingTop: 0,
  },
  configItem: {
    backgroundColor: '#f9fafb',
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
  },
  configLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: '#6b7280',
    marginBottom: 4,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  configValue: {
    fontSize: 13,
    color: '#111827',
    fontFamily: 'monospace',
    fontWeight: '500',
  },
  dashboardLink: {
    backgroundColor: '#111827',
    borderRadius: 12,
    padding: 16,
    alignItems: 'center',
    marginTop: 8,
  },
  dashboardLinkText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#fff',
  },
  passkeyLink: {
    paddingVertical: 24,
    paddingHorizontal: 24,
    backgroundColor: '#f9fafb',
    alignItems: 'center',
  },
  passkeyLinkText: {
    fontSize: 16,
    color: '#4f46e5',
    fontWeight: '500',
  },
  footer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 32,
  },
  footerText: {
    fontSize: 14,
    color: '#9ca3af',
    fontWeight: '500',
  },
  footerLogoContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  footerLogoCircle: {
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: '#000',
    marginHorizontal: 6,
  },
  footerLogoText: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#000',
    letterSpacing: -0.5,
  },
  logoImage: {
    width: 18,
    height: 18,
  },

  // Fingerprint Icon Styles
  fingerprintIcon: {
    width: 20,
    height: 20,
    marginRight: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  fingerprintOuter: {
    position: 'absolute',
    width: 16,
    height: 16,
    borderRadius: 8,
    borderWidth: 1.5,
    borderColor: '#6b7280',
    borderStyle: 'dashed',
  },
  fingerprintMiddle: {
    position: 'absolute',
    width: 12,
    height: 12,
    borderRadius: 6,
    borderWidth: 1.5,
    borderColor: '#6b7280',
  },
  fingerprintInner: {
    position: 'absolute',
    width: 8,
    height: 8,
    borderRadius: 4,
    borderWidth: 1.5,
    borderColor: '#6b7280',
  },
  fingerprintCore: {
    position: 'absolute',
    width: 4,
    height: 4,
    borderRadius: 2,
    backgroundColor: '#6b7280',
  },

  // Wallet Icon Styles
  walletIcon: {
    width: 20,
    height: 20,
    marginRight: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  walletBody: {
    width: 16,
    height: 12,
    borderWidth: 1.5,
    borderColor: '#6b7280',
    borderRadius: 3,
    backgroundColor: 'transparent',
    position: 'relative',
  },
  walletFlap: {
    position: 'absolute',
    top: -1.5,
    left: 2,
    right: 2,
    height: 3,
    backgroundColor: '#f9fafb',
    borderTopWidth: 1.5,
    borderLeftWidth: 1.5,
    borderRightWidth: 1.5,
    borderColor: '#6b7280',
    borderTopLeftRadius: 2,
    borderTopRightRadius: 2,
  },
  walletCard: {
    position: 'absolute',
    bottom: 2,
    left: 2,
    width: 8,
    height: 1.5,
    backgroundColor: '#6b7280',
    borderRadius: 0.5,
  },
});
